### ISSUE TITLE
Create the Stories List page

### ISSUE THREAD

**Issue by rsundar** [Collaborative-Content/MintingPress#17]
## TASKS

- [x] Create the stories list page with all active/new stories
- [x] Get the content token ID from the contract and the associated story
- [x] Render StoryCards with all active/new stories
